### ISSUE TITLE
[QUESTION] Live streaming  using Shaka streamer to Replay react app

### ISSUE THREAD

**Issue by LSrt-stack** [vimond/replay#19]
Hi,
      Am trying to use Replay to stream a live DASH feed. the DASH is generated using Shaka Streamer.  For some reason the live feed buffers, or the live video seek bar jumps back and forth unpredictably. Can you throw some insight into it ? 

VOD is fine with no issues.

Thank you

**Comment by torerikal** [comment]
Live DASH playback is supported through [Shaka Player](https://github.com/google/shaka-player). If the same behaviour can be observed in their [demo player](https://shaka-player-demo.appspot.com/demo/#audiolang=nb;textlang=nb;uilang=nb;panel=HOME;build=compiled), there is a more general problem with your live stream outside the scope of this project.
