### ISSUE TITLE
[BUG] includeControls not working properly

### ISSUE THREAD

**Issue by simoneTocket** [vimond/replay#23]
When specifying the controls needed, using includeControls, some of them does not appear on the player (e.g. volume, skipButton, gotoLiveButton..)

**Comment by torerikal** [comment]
Please have a look at this example specifying some of the controls you mention. For me all show up, however note that the Go to live button is only visible when playing live streams.

https://codesandbox.io/s/replay-autoplay-erwl2?fontsize=14&hidenavigation=1&theme=dark

If you still have problems getting the desired controls to show up, please provide a code example.

**Comment by simonedaini** [comment]
Thanks for your reply. I checked the example and, on my browsers (Chrome, Mozilla and Edge), the volume slider does not appear on the player if it is selected through includeControls. If i use all the controls, removing includeControls, the volume slider appears the player instead. I solved masking the unwanted controls with CSS, but i cant figure out why the volume does not behave like the other controls.

**Comment by torerikal** [comment]
I was having a second look after your reply, and I then saw the issue. Good to hear that you already worked around the issue. 

I have anyhow created a fix to this. Release 2.0.2 should include `volume`, and all the 14 other possible controls that can be specified, according to the documentation.
