### ISSUE TITLE
[BUG] Autoplay not working 

### ISSUE THREAD

**Issue by simoneTocket** [vimond/replay#24]
Even if the initialPlaybackProps "isPaused: false" is specified, the video does not play automatically.

<Replay source={props.url} initialPlaybackProps={{ isPaused: false }}> 
    <HlsjsVideoStreamer />
</Replay>

**Comment by torerikal** [comment]
Most browsers might block autoplay of videos according to different policies. Often only muted autoplay is allowed, before a web site is whitelisted. This is not something Replay is capable of bypassing. Here is a guide to autoplay restrictions.

https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

This example starts playing in Chrome, but not in Safari, according to my settings where I have chosen to not allow autoplay:

https://codesandbox.io/s/replay-autoplay-erwl2?fontsize=14&hidenavigation=1&theme=dark

I suggest you experiment `isMuted: true/false` to see if that changes how `isPaused: false` works for you,
