### ISSUE TITLE
Placeholder image

### ISSUE THREAD

**Issue by drez** [vimond/replay#25]
Hi! Is there a way to set a custom start image?
Thanks.

**Comment by torerikal** [comment]
The player itself doesn't facilitate displaying a start/end poster before and after playback. As suggested in the [docs](https://vimond.github.io/replay/#/replay/insert), this is better handled outside the player, in your app.

This [code sandbox](https://codesandbox.io/s/quirky-goodall-tw47z?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.tsx:261-280) implements a visually primitive, but functioning example of adding a start poster, implemented with the React useState hook. The Replay logo serves as the "start image", but any photo or graphics can be specified in the src tag. 

Also note that I have added an exit button to the player through specifying the onExit handler, which then can be used to go back to the image.

Hope this covers what you need for building your web site around the Replay player.
