### ISSUE TITLE
Compile error with typerscript

### ISSUE THREAD

**Issue by drez** [vimond/replay#26]
Hi!
I am getting compile error with @types/react 16+, typescript 3.5.3

node_modules/vimond-replay/index.d.ts(3,37):
TS2694: Namespace 'React' has no exported member 'Element'.
node_modules/vimond-replay/index.d.ts(3,37):
TS2307: Cannot find module './PlayerConfiguration' or its corresponding type declarations.
node_modules/vimond-replay/video-streamer/VideoStreamer.d.ts
TS2307: Cannot find module '../Replay' or its corresponding type declarations.

I am fairly new to react typescript so I may be out of place here, but I have been looking around a lot and haven't found a way to correct the problem.

**Comment by torerikal** [comment]
Not sure what happens here. The [code sandbox](https://codesandbox.io/s/quirky-goodall-tw47z?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.tsx:261-280) I set up for your other question is using Typescript. Please have a closer look on tsconfig.json, package.json, TypeScript and React versions from that example and see if you find something different or missing in your setup.

You can also compare with [this project](https://github.com/vimond/streamlab), which is also built with Typescript and uses the *.d.ts declaration files that your error message refers to.

**Comment by drez** [comment]
Hi! Thanks for the help. I found a work around comparing the projects you proposed. Setting ""skipLibCheck": true," in tsconfig did the trick. I am not sure its a long term solution tho.
