### ISSUE TITLE
[BUG] PlayReady license acquisition not working

### ISSUE THREAD

**Issue by kevinlethe** [vimond/replay#29]
ShakaVideoStreamer does not retrieve PlayReady license

When attempting to play a DASH stream protected by PlayReady DRM, no call is made to the license acquisition URL and playback fails.  However, the same stream can be played in the Shaka demo player.

This simple example demonstrates the issue using a Microsoft test stream:

import React from 'react';
import { Replay } from 'vimond-replay';
import 'vimond-replay/index.css';
import ShakaVideoStreamer from 'vimond-replay/video-streamer/shaka-player';

const source = {
  streamUrl: 'https://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/manifest(format=mpd-time-csf)',
  contentType: 'application/dash+xml',
  licenseUrl: 'https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(persist:false,sl:150)',
  drmType: 'com.microsoft.playready',
};

function App() {
  return (
< Replay
      source={source}
    >
      < ShakaVideoStreamer />
    < /Replay>
  );
}

**Expected behavior**

The stream should play.

**Screenshots**

If applicable, add screenshots to hselp explain your problem.

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] Windows 10 (10.0.18363.1500)
 - Browser [e.g. chrome, safari] Edge 90.0.818.46

**Additional context**
React 16.13.1
vimond-replay 3.0.0

 - React version.
 - Video/stream URL, characteristics (e.g. DVR, subtitles) and stream technologies (DASH, HLS) related to the problem.
 - Add any other context about the problem here.

**Comment by torerikal** [comment]
Thank you for your report. Your setup looks right. Unfortunately PlayReady is only available in Windows Edge, and I don't have Windows easily available at the moment. This means I can't test successful PlayReady DRM playback in the Shaka demo page or in Replay right now.

Immediately it seems to me that the license details are passed on correctly to Shaka Player in the ShakaVideoStreamer code, but I should try to get hold of a Windows machine so I can troubleshoot further.

Meanwhile, could you please check if the example stream plays or fails in a Replay test player page? The link underneath includes the example stream details, but in the form please verify that PlayReady is displayed/selected as technology right to the license URL, and that MPEG-DASH is selected as technology right to the DASH manifest URL:

https://vimond.github.io/streamlab/?s={%22streamDetails%22:{%22streamResource%22:{%22url%22:%22https:%2F%2Fprofficialsite.origin.mediaservices.windows.net%2Fc51358ea-9a5e-4322-8951-897d640fdfd7%2Ftearsofsteel_4k.ism%2Fmanifest(format%3Dmpd-time-csf)%22,%22headers%22:[],%22useProxy%22:false,%22technology%22:1},%22drmLicenseResource%22:{%22url%22:%22https:%2F%2Ftest.playready.microsoft.com%2Fservice%2Frightsmanager.asmx%3Fcfg%3D(persist:false,sl:150)%22,%22headers%22:[],%22useProxy%22:false,%22technology%22:2},%22drmCertificateResource%22:{%22url%22:%22%22,%22headers%22:[],%22useProxy%22:false,%22technology%22:2},%22subtitlesResource%22:{%22url%22:%22%22,%22headers%22:[],%22useProxy%22:false,%22technology%22:0},%22isDrmCertificateApplicable%22:true,%22startOffset%22:%22%22},%22playerOptions%22:{%22logLevel%22:2,%22showPlaybackMonitor%22:false,%22customConfiguration%22:%22%22,%22playerLibrary%22:%22AUTO%22}}

If it fails, please share error details from the console.

**Comment by kevinlethe** [comment]
The video plays on the that page and there are no errors in the console.

**Comment by torerikal** [comment]
Thanks for checking. This page uses the same version of Replay and React as you have reported for your test.

One reason for DRM not working might be the host name from where you expose your test React app with the PlayReady example. Chrome and probably Chromium Edge only allows DRM to work with "secure hosts". This means either you have to use "http://**localhost**" or a "**https**://anything" URL in order to enable DRM. Other host names or IP addresses with http only won't work.

What host name and protocol do you use in your React app test? E.g. http://localhost:8080 (which should work), or something more custom?

Reference for the "secure url" requirement. https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html

**Comment by kevinlethe** [comment]
That is the problem.  I was using a Windows test machine to connect the development server on my Mac.  Once deployed to a server with a proper SSL certificate is does work correctly.

Thank you so much for the help.
