### ISSUE TITLE
[QUESTION]  How do I pause a video with a mouse click?

### ISSUE THREAD

**Issue by xeleoss** [vimond/replay#36]
I click on the video, but there is no pause. It is placed only when you click on the button. 
In the documentation, I found the setting of keys from the keyboard. I tried to write togglePause: ['click'] and so on, but it didn't help.

**Comment by torerikal** [comment]
There is no play/pause toggle overlay on top of the video area. You can add your own by creating your own custom player UI, as described here: https://vimond.github.io/replay/#/custom-player/add-controls-components
