### ISSUE TITLE
[ERROR] "Package size exceeded the configured limit of 100 MB

### ISSUE THREAD

**Issue by Enigma10** [vimond/replay#39]

**Comment by torerikal** [comment]
Thanks for reporting this issue. I have removed unnecessary documentation files bloating the package. A new version 3.2.1 is released, providing a radically smaller package size of 1.5 MB (unpacked).

**Comment by TiagoPortfolio** [comment]
Hi all!

I tried to install version **1.12.1** of this package but yarn is taking too long to download it.
I checked the size of it and, according to https://registry.yarnpkg.com/vimond-replay/-/vimond-replay-1.12.1.tgz, this file has **96.5 MB** in size which is way too much when compared with the latest version (286,8 kB).

Should a new issue be opened for this?

**Comment by Enigma10** [comment]
@TiagoPortfolio You can download the new version 3.2.1 which is having a lower size

**Comment by torerikal** [comment]
Thanks for pointing this out @Enigma10. @TiagoPortfolio, the changes in the newer major versions are mainly updates to the underlying player libraries. I hope the latest version works for you, as there will be no fixes released reducing the size of version 1.x.
