### ISSUE TITLE
[BUG] DASH playback broken with Shaka Player v3.2.1

### ISSUE THREAD

**Issue by buzzie-bee** [vimond/replay#43]
**Describe the bug**

After running npm update I noticed that my dash streams were no longer playing. After investigating the issue it seems that the shaka-player version 3.2.1 does not work as expected with vimond-replay. The player seems to be stuck in an 'inactive' state and does not play .mpd dash videos.

**To Reproduce**

I have created a code sandbox where you can change the shaka-player version from the default 3.2.1 to the last working 3.1.3 version. 

https://codesandbox.io/s/broken-sun-dh1s0

This is using the demo .mpd file used in the vimond-replay docs.

https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

Alternatively, you can spin up a new create-react-app app and run `npm install vimond-replay`, and use the following code from the website example to reproduce:

```jsx
import { Replay } from "vimond-replay";
import ShakaVideoStreamer from "vimond-replay/video-streamer/shaka-player";
import "vimond-replay/index.css";
import "./styles.css";

export default function App() {
  return (
    <div className="App">
      <Replay
        source="https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd"
        initialPlaybackProps={{ isPaused: true }}
      >
        <ShakaVideoStreamer />
      </Replay>
    </div>
  );
}
```
Finally you can git clone the vimond-replay repository and run npm install (potentially may require deleting package.lock and node_modules to ensure latest 3.2.1 version is installed).

Running the app and entering https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd as the source does not play the video after closing the mock player.

Changing the package.json `"shaka-player": "^3.1.1"` version to `"shaka-player": "~3.1.1"` and reinstalling dependencies makes the player work again.

**Is the problem actually a Replay bug?**

I have confirmed that the .mpd file plays successfully on the shaka-demo pages.

https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**Expected behavior**

I would expect vimond-replay to play dash .mpd files.

**Screenshots**

![image](https://user-images.githubusercontent.com/39500959/145724378-c07c9426-5c00-41d0-991d-5385cbc52aae.png)

**Desktop (please complete the following information):**

 - OS: Pop!_OS v21.04
 - Browser Both Firefox v95.0 and Chromium v96.0.4664.45

**Additional context**

"react": "^17.0.2"
"vimond-replay": "^3.2.0"

Video/stream URL: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**Comment by torerikal** [comment]
Thanks @buzzie-bee for your bug report. 

The initial investigations indicate that a hard polyfill dependency might have been introduced in the latest Shaka Player version. Shaka Player tries to consume some properties on `window.shakaMediaCapabilities`, which you through the console can see is present in the Shaka demo page, but not in pages with Replay.

As a quick fix to your issue, these polyfills can be enabled by config. Please see my addition to your example in [the code sandbox](https://codesandbox.io/s/practical-sunset-yzv1i?file=/src/App.tsx) or here:

```
<Replay
  source="https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd"
  initialPlaybackProps={{ isPaused: true }}
  options={{
    videoStreamer: {
      shakaPlayer: {
        installPolyfills: true
      }
    }
  }}
>
  <ShakaVideoStreamer />
</Replay>
```

Setting `installPolyfills` to `true` will make the ShakaVideoStreamer execute `shaka.polyfill.installAll()` upon inserting the player.

There are several changes to Shaka's polyfills in the [latest releases](https://github.com/google/shaka-player/releases). I will read a bit more up on those before making adjustments to Replay's Shaka integration.

**Comment by buzzie-bee** [comment]
Thanks for the quick response @torerikal 

Sorry for not getting back to you sooner. It was a pretty crazy week getting ready for Christmas. I managed to get everything working by fixing the version of shaka player in the package.json to "shaka-player": "~3.1.1". 

I just tried setting the options on the Replay component as you suggested, but typescript is kicking off saying ''shakaPlayer' does not exist in type 'VideoStreamerConfiguration'.' 

It does play successfully in the sandbox, but after a few seconds of loading the same TS errors are being thrown.

It looks like this 'shakaPlayer' option isn't listed in the PlayerConfiguration.d.ts file.

All is working ok for now so with the hardwired shaka-player version so no rush on the changes. Let me know if I can help at all.

**Comment by torerikal** [comment]
@buzzie-bee I have published a [new patch version](https://github.com/vimond/replay/releases/tag/v3.2.2) for `vimond-replay`, where the polyfill for `MediaCapabilities` is always installed. This should then eliminate the need for specifying `installPolyfills: true`. Still, I added this and other player library-related configuration properties to the TypeScript definitions (although keeping it a bit simple, not referring the third party library type definitions).

Thus, closing this issue for now. Please report if you see additional problems.
