### ISSUE TITLE
[QUESTION] Turn off pointer events?

### ISSUE THREAD

**Issue by kunaljaypatel** [vimond/replay#46]
Is there a publicly exposed way to turn off pointer events or disable downloading?

I want to prevent users from being able to right-click download video.

**Comment by torerikal** [comment]
@kunaljaypatel Sorry, there is no API for this, as such measures have almost no real effect in preventing downloads. 

[This StackOverflow answer](https://stackoverflow.com/questions/63661423/disable-the-save-as-button-from-videos-like-youtube/63674458#63674458) provides a good discussion on why. It also shows a way you can implement it without an API.

**Comment by kunaljaypatel** [comment]
> @kunaljaypatel Sorry, there is no API for this, as such measures have almost no real effect in preventing downloads.
> 
> [This StackOverflow answer](https://stackoverflow.com/questions/63661423/disable-the-save-as-button-from-videos-like-youtube/63674458#63674458) provides a good discussion on why. It also shows a way you can implement it without an API.

thank you.
