### ISSUE TITLE
[QUESTION] Documentation on audio tracks

### ISSUE THREAD

**Issue by hackntest** [vimond/replay#51]
I can't find any information about how audio tracks are handled. Can I load external audio tracks as it is done with subtitles, or am I limited to the audio tracks that the video file contains? How do I define and reference the audio tracks a video file contains so the player displays the switch?

**Comment by torerikal** [comment]
Sorry for a late reply. Additional audio tracks need to be part of the file or stream, so this is different to subtitle files. MP4 files can be created with multiple audio tracks through commonly used tools like ffmpeg.
