### ISSUE TITLE
[QUESTION] Does this player work with React Native?

### ISSUE THREAD

**Issue by zclcdco** [vimond/replay#54]
Hello,
Can I implement this player in a React Native app?

Also, is it compatible with Smart TV's in-built browser?

Thank you.

**Comment by torerikal** [comment]
Sorry for a late reply. The player is built on top of the browser's video playback functionality, and does likely not work or at least not work well with React Native. It is not likely to work very well with smart TV browsers either, but that probably depends on the types of video files or streams you want to play in it.
