### ISSUE TITLE
[BUG] Two replay players on one tab browser in the same time occur browser suspending

### ISSUE THREAD

**Issue by marek-krzak-bsg** [vimond/replay#55]
**Is the problem actually a Replay bug?**

Yes, it is. On the latest version on Replay. It isn't related with stream or its quality.
!!! Update. I tested only with one source stream and works but when source streams are different, something is wrong like described below. 

**Describe the bug**

When I put two or more Replay player on one page and they start playing movies the browser suspending.

It's quite random because sometimes the problems occur right away but sometimes are increase by interaction with video layer like mouse move over or click on something play/volume button. Generally problems occurs quickly.

At the beginning movies restarts and autoplays and finally browser is suspended. Console is clean. But a lot of request for video streams are generate. 

**To Reproduce**

1. Create two Replay player on page and add stream to them.
2. Click play on first video and next for second.
3. Interact with video layer like mouse over or click button
4. They we are some video problems and finally browser is suspended.

**Expected behavior**

Two or more videos will be playing together at the same time. And browser will be healthy.

**Screenshots**

No needed.

**Desktop (please complete the following information):**

 - OS: iOS
 - Browser chrome, safari
 - Version 12.3.1

**Smartphone (please complete the following information):**

No tested

**Additional context**

Null

**Comment by torerikal** [comment]
Sorry for a late response. I have tested adding two Replay instances to a page. I have tried this page out on an iPhone 12 with iOS version 15.4.1. Unfortunately I have not been able to reproduce the described issue. 

In my tests, I have used a combination of some HLS streams and MP4 files. I do see an issue with one of the HLS streams where seeking stops working correctly after many repeated attempts. This happens both when dragging the slider or purely programmatically, by invoking JS commands, setting the currentTime property directly on the video element inserted by Replay. It could or could not be related to your observations. 

In my tests, the browser is not suspended or having other issues. I have also recorded a performance timeline from my attempts, without seeing anything remarkable in terms of script activity running wild.

I am afraid this is more of an issue with the iOS browser engine (used in both Safari and Chrome), and perhaps it could be dependent of the iPhone hardware or the not so recent version of iOS, if running the older version 12.3.1, as stated. With the current information provided, no more investigations will be done by me at this time.
